Bumping nesting indexer to v0.3.0
This resolves a bug found in the tests:

```shell

2) FeaturedCollectionList featured_collections when one of the files is
   deleted is a list of the remaining featured collection objects, each
   with the collection's solr_doc

Failure/Error: collection1.destroy

NoMethodError:

  undefined method `each' for true:TrueClass

/usr/local/bundle/gems/hyrax-2.9.6/app/models/concerns/hyrax/collection_nesting.rb:35:in `update_child_nested_collection_relationship_indices'
/usr/local/bundle/gems/active-fedora-12.2.3/lib/active_fedora/callbacks.rb:231:in `destroy'
./spec/models/featured_collection_list_spec.rb:28:in `block (4 levels) in <top (required)>'
```